zegami/zegami-cli

- zeg/datasets.py
Wrapped create_engine function uses a different keyword argument
name from that used by sqlalchemy.
> Fix unexpected keyword argument 'echo'

- zeg/http.py
- zeg/imagesets.py
Based on browser connection-per-hostname limits, clients should
probably have fewer open connections than the five-times-cpus that
the thread pool defaults to.
> Limit concurrent api requests to 16

- tox.ini
- zeg/auth.py
- zeg/imagesets.py
- zeg/log.py
Run tests on py34, py35, and py36, and lint with flake8.
Install run `tox` to use, though getting older Python binaries is an additional step.
Note, Python 3.4 passes as test coverage isn't all there yet, it should fail.
> Add tox config for tests on many Python versions

- zeg/datasets.py
Don't need the file name (unless the CLI is running in the same dir as
the file).
> Path not name

- setup.py
Descriptions that are not in reStructuredText format require the content
type to be specified as "text/markdown" instead. See
https://pypi.org/help/#description-content-type
> Long description content type

- zeg/imagesets.py
Should output the nice error message alongside the cryptic `NoneType has no attribute 'split'`
> Give a useful error message if no Azure Connection String Env Var is set

- requirements/test.txt
- setup.py
- tox.ini
- zeg/imagesets.py
Had an older version of SQLAlchemy pinned which attempts to use the
deprecated `time.clock()` on win32.
Update all dependencies and tox config to catch this issue with extra
packages when run on win32 at least.
Fix one lint error that snuck in.
> Fix import on windows with Python 3.8/SQLAlchemy

- zeg/http.py
- zeg/tests/test_http.py
It's possible to get a signed URL back from azure projects but PUTs will fail because we don't properly handle them in http, this just adds the required header if the request is going to azure.
> Provide appropriate headers with PUTs to azure using http

- setup.py
Release drafted, will update requirements on e2e tests to include the new version.
> Version bump to 1.1.7

- README.md
End users will probably never use this argument, and it is adequately described elsewhere.
> Update Readme to remove the token argument from all examples

- zeg/collections.py
- zeg/http.py
- zeg/imagesets.py
Took a while to understand `futures` and understand where the bottlenecks where, but this a bit of an excerpt that should be much faster assuming the bulk endpoint is available in cloud. That's in a separate pr on `zegami-cloud`
> Batch image upload operations in the CLI

- zeg/imagesets.py
I had it set to 1 during development and forgot to change it back, so uploads are bottlenecked by http latency.
> Concurrency fix

- zeg/imagesets.py
This fixes a rather critical issue where updating an existing imageset could result in overwriting from 0, had a bit of tunnelvision when first implementing this that the thought of updating an imageset after the fact escaped my mind. This effectively avoids the problem by always starting from the end of an imageset.
Only potential problem, if the upload process is cancelled/stopped prematurely, there will be lots of nulls in the imageset.
> Write from the end of an imageset rather than from 0 every time

- setup.py
- zeg/imagesets.py
Somewhat messy change intended to be reverted once a broader fix for nulls in cancelled uploads has been landed.
There is an issue with extending imagesets that mean nulls persist when the user cancels or otherwise fails to complete a CLI upload.
> Use slow path upload for now

- setup.py
- zeg/imagesets.py
This reintroduces the bulk operations on the imageset and makes use of the endpoint which removes instances of 'None' and replaces with a placeholder. This means updating an imageset after a failed run is also possible, the imageset would just be extended again and all the previous instances of 'None' would be replaced when the second run completes.
> Re-enable fast uploads with post-upload clean step

- zeg/imagesets.py
The cloud portion of the PR updated to allow JSON post but the CLI was attempting a GET - this results in a 405. Just need to update the CLI to attempt a POST instead.
> Update endpoint to use POST rather than GET

- .flake8
- tox.ini
- zeg/imagesets.py
When recursively scanning directories but forcing mime type with image only collections, sometimes junk such as `thumbs.db` (windows) and `.DS_Store` (mac) get uploaded which causes erroneous entries in the collection. Similarly the `.yaml` file is obviously not an image, so along with a few other obvious entries, check against a blacklist when ignoring mime type.
> Ignore some file types/extensions even when forcing mime type

- zeg/imagesets.py
Attempting to upload a file larger than 256MB will result in a yellow warning.
Additionally the total upload file-size will be output when the verbose flag is provided.
Example:
```
One or more files exceeds 256MB, collection processing may be unreliable.
Total upload size: 2.42GB
0%|                                                             | 0.00/4.00 [00:00<?, ?image/s]
```
> Warn when uploading files larger than 256MB

- zeg/imagesets.py
Extend imageset file blacklist to include commonly used data file format extensions
https://zegami.atlassian.net/browse/ZGM-6327
> Extend imageset file blacklist

- zeg/imagesets.py
This was going to be a much bigger PR with some overhauls on the upload progress and how we use `tqdm` to use current/total upload bytes for progress rather than iteration on the `as_completed` future iterator, but that's a bigger bite than worth chewing right now given the measure of testing & fiddling required to get it right so I've raised a task to improve this, I did try but it wasn't super straightforward to implement consistently.
Also removed duplicate entry on the blacklist for `.yaml`.
> Fix a typo when reporting filesize for upload

- setup.py
- zeg/__main__.py
- zeg/projects.py
Use like `zeg list projects`, example:
```
matthewhall@Matthews-Mac-mini zegami-cli % zeg list projects -u https://staging.zegami.com --v
GET: https://staging.zegami.com/oauth/userinfo/
=========================================
list projects with result:
-----------------------------------------
3q7if47h: matt+azure@zegami.com's workspace
idUpFsFf: ahaith Azure
=========================================
```
> Add command for listing projects available to current user

- zeg/imagesets.py
We used to create this new dz_json and replace the old one because we created a new join dataset. But as we are only making PUT request to join dataset now, the join dataset id doesn't change so there's no need to make any changes to dz_json anymore.
> Remove creating a new dz_json and replacing the old one

- zeg/collections.py
- zeg/config.py
This happens in the parse_config function as otherwise
the configuration cannot be validated in the validate_config function
Removed the casting from collections.py as it's not needed anymore
https://zegami.atlassian.net/browse/ZGM-6706
> Casting the name to string before validation

- zeg/config.py
The previous PR broke any actions other than creating collections
As only collection creation requires a name in the config
> This is a fix for PR #93

- zeg/collections.py
- zeg/imagesets.py
Relates to the change [PR](https://github.com/zegami/zegami-cloud/pull/978) because we made `source_id` different with `source_name`
> Compare with source_name rather than source_id

- zeg/collections.py
- zeg/schemata/spec.yaml
Add `use_wsi` flag
Have tested that the wsi collection is successfully created and published on top of [PR](https://github.com/zegami/zegami-cloud/pull/1013)
https://zegami.atlassian.net/browse/ZGM-7078
> Support creating wsi collection

- setup.py
Now a less strict version spec, and matches zegami-python-sdk.
Bump version
> Update azure-storage-blob version
