zegami/zegami-cli

README.md, zeg/__main__.py, zeg/collections.py, zeg/log.py
Added `all` option to list all collections in the project.
Added flag to json print to prevent shortening of long lists.
=> Get all collections

README.md, setup.py, zeg/config.py, zeg/datasets.py, zeg/http.py, zeg/imagesets.py
Upload images in parallel with progress bar.
=> Imageset update

README.md, setup.py, zeg/datasets.py
Query a database in order to update a data set
=> SQL Query support

README.md, zeg/collections.py, zeg/datasets.py, zeg/http.py
Update can be used to publish or unpublish a collection
=> Publish collection

README.md, zeg/imagesets.py
This join was missing which was causing uploaded images not to be
included in the collection
=> Dataset join

README.md
Was `dataset` instead of `imageset`
=> Copy paste error

setup.py, zeg/config.py, zeg/datasets.py, zeg/imagesets.py, zeg/schemata/spec.yaml, zeg/tests/__init__.py, zeg/tests/test_config.py
Implemented jsonschema to validate configuration files
=> Config validation

README.md, requirements/test.txt, setup.py, tox.ini, zeg/collections.py, zeg/config.py, zeg/http.py, zeg/imagesets.py, zeg/schemata/spec.yaml, zeg/tests/__init__.py, zeg/tests/test_imagesets.py
Also ensured that http errors are printed twhen throwing badrequest.
=> Added url imageset possibilitiy to update imageset.

zeg/http.py, zeg/tests/test_http.py
These should really be switched to 204 in the front end but don't want
to change all clients right now.
=> Empty responses are still sometimes sent with 200.

setup.py
=> PyODBC version bump

setup.py, zeg/__main__.py
Switched to `zegami.com` instead of `app.zegami.com`
=> Updated hostname

README.md, requirements/test.txt, setup.py, zeg/__main__.py, zeg/collections.py, zeg/config.py, zeg/datasets.py, zeg/imagesets.py, zeg/schemata/spec.yaml
Take an input file with data and image locations and create a collection
=> Add ability to create a collection

zeg/config.py
Addresses PyYAML load deprecation warning
=> PyYAML load warning

setup.py
=> Version 1.1.2 bump

README.md
Documented steps to create a Zeg collection from a PostgreSQL database
=> Added PostgreSQL documentation

setup.py, zeg/azure_blobs.py
Switched the azure module for the more specific azure-storage-blob to
reduce unused module bloat
=> Removed azure dependency

setup.py, zeg/http.py
Will help with https://zegami.atlassian.net/browse/ZGM-4824
=> Use same retry backoff for http requests as zegami-cloud

setup.py, tox.ini
Updated setup.py to include compatability with Python 3.8
=> Python 3.8 support

setup.py
Updated version number in `setup.py`
=> Version 1.1.5 Bump

azure-pipelines.yml, tox.ini
Validate with latest Python on both linux and windows.
Add new yaml config to yamllint check.
Adding gating, through new public project on Azure DevOps with pipeline.
=> Add configuration for Azure Pipelines gating

setup.py
Tweak setup.py a little as well to match current status.
=> Bump to version 1.1.6 for release

README.md, zeg/__main__.py, zeg/collections.py, zeg/config.py, zeg/schemata/spec.yaml, zeg/tests/test_config.py
- Added data filetype validation
- Improved schema validation feedback
- Updated schema validation tests to expect the error message returned
- readme updates
=> Cli qol updates

README.md
- Include explanations of project id, collection id and dataset id and how to retrieve them to be used in different cli commands.
=> Update CLI readme

zeg/imagesets.py
- Make a PUT request to update the existing join dataset with the dataset_column rather than creating a new join dataset and replace the existing one. This will be the same behaviour as new collection creation.
=> Update join dataset rather than creating a new one

zeg/collections.py
=> Return collection object from create

zeg/collections.py
replace empty description with an empty string
https://zegami.atlassian.net/browse/ZGM-5676
=> Fix empty description in yaml throws bad request 400

README.md, zeg/imagesets.py, zeg/schemata/spec.yaml, zeg/tests/test_config.py
https://zegami.atlassian.net/browse/ZGM-5766
=> Support file based imageset and datasets for auto column selection

README.md, setup.py, zeg/imagesets.py, zeg/schemata/spec.yaml
https://zegami.atlassian.net/browse/ZGM-5880
Companion change to https://github.com/zegami/zegami-cloud/pull/810
=> Allow custom headers to be used when fetching images for a url imageset

zeg/imagesets.py
I'm hesitant to do the join before images have uploaded for other imagesets due to the way they work (could start processing before it's populated). But in the case of file imagesets, it should be filled with nulls until it is complete so it's perhaps fine to do the join before it's ready as it should only start processing when the images are populated or the `replace_empties` endpoint has been hit.
The issue before was that even if you cancelled, the join happens after the imageset upload in the CLI code - so whilst the upload imageset was fine, there was no join so the collection would be stuck at the `image column not chosen` status.
=> Pre-emptive join for file imageset

README.md, zeg/collections.py, zeg/schemata/spec.yaml, zeg/tests/test_config.py
- No need to upload the data file and update the `upload_dataset` if `path ` is not provided.
- Updated yaml, test and Readme
=> Allow images only collection with CLI

zeg/imagesets.py
Include `processing_category` and `node_groups` for CLI update the join dataset during collection creation
https://zegami.atlassian.net/browse/ZGM-6326
=> Include processing_category and node_groups for join dataset

setup.py, zeg/collections.py
There was a missing argument from a function in `collections.py`
Bumped the version
=> Fixed an issue with publishing collections

README.md, setup.py, zeg/collections.py, zeg/imagesets.py, zeg/schemata/spec.yaml
- Updated schema for the multiple image sources creation yaml file. This should support file based, URL based and azure container imagesets. I have only tested file based ones. More thorough tests are required.
- Updated collection creation process to handle it
- Updated readme
=> Multiple image sources collection creation

setup.py, zeg/collections.py, zeg/imagesets.py
Changes according to [PR](https://github.com/zegami/zegami-cloud/pull/926)
Bump to 1.5.1
=> Update multi source creation to work with new shape of image_sources 

zeg/collections.py
https://zegami.atlassian.net/browse/ZGM-6706
=> Cast name to string before making request to create collection

README.md, zeg/schemata/spec.yaml
https://zegami.atlassian.net/browse/ZGM-6738
=> Update schema to require dataset for multisrc collection

zeg/collections.py, zeg/schemata/spec.yaml
CLI changes for [PR](https://github.com/zegami/zegami-cloud/pull/967)
Also add required field name for collection schema
=> Able to configure whether to have image info for v2 collection

zeg/datasets.py, zeg/imagesets.py
https://zegami.atlassian.net/browse/ZGM-7440
=> Update uploaded blob id to be imagesetsORdatasets/<upload_id>/<uuid()>

requirements/test.txt, zeg/imagesets.py, zeg/tests/test_imagesets.py
https://zegami.atlassian.net/browse/ZGM-8305
=> Use new fetch node for URL imageset

requirements/test.txt, zeg/imagesets.py, zeg/tests/test_imagesets.py
It requires further enhancement to deal with failing to download images
=> Revert new fetch node
